### ISSUE TITLE
milkdown编辑器问题

### ISSUE THREAD

**Issue by jiandandaoxingfu** [maki-math/maki-web-hexo#21]
打开添加题目， milkdown编辑器会出现如下图的问题
![milkdown-bug](https://user-images.githubusercontent.com/33108686/152488958-285ba416-d701-4546-ad34-33478144cb6f.png)

**Comment by suica** [comment]
这个应该是由于采用的图标字体来自google font，国内访问可能有问题。之后会找个正常的cdn
