### ISSUE TITLE
注册失败

### ISSUE THREAD

**Issue by YoonaLimSauce** [maki-math/maki-web-hexo#57]
现在是有什么特殊原因不支持注册吗?
还是注册有什么注意事项

**Comment by suica** [comment]
回复迟了不好意思。请检查用户名是否可能重复、用户密码是否足够复杂。

**Comment by suica** [comment]
Duplicate of #55

**Comment by YoonaLimSauce** [comment]
> 回复迟了不好意思。请检查用户名是否可能重复、用户密码是否足够复杂。

主要是想建议一下
可以加一个提示失败的原因
只提示了一个"注册失败"的提示信息
不知道哪里不符合要求, 不方便修改, 就想提个建议

**Comment by suica** [comment]
@YoonaLimSauce 
已经在 352edf7a020614d540c2d0dc94a30bd0e0b26175 中修复，请看看现在行为是否符合预期 :)
